name: flutter_decorated_text_example
description: flutter_decorated_text example
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_decorated_text:
    path: ../
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true