name: flutter_decorated_text
description: >-
  Set different rules to the DecoratedText widget to style differently what each rule matches.
  Add onTap callback to rules and get the matching text
version: 1.0.7
repository: https://github.com/gabdsg/flutter_decorated_text

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
flutter: