name: flutter_decorated_text
description: >-
  Set different rules to the DecoratedText widget to style differently what each rule matches.
  Add onTap callback to rules and get the matching text
version: 1.0.6
repository: https://github.com/gabdsg/flutter_decorated_text

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
flutter: