name: flutter_decorated_text
description: Decorated text package
version: 1.0.2
repository: https://github.com/gabdsg/flutter_decorated_text

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: