name: flutter_decorated_text
description: >-
  A widget to style and interact with parts of a text based on rules. Match words, phrases, or patterns and apply custom styles or actions.
version: 2.0.2
repository: https://github.com/gabdsg/flutter_decorated_text

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter: